sudo: required

language: bash

services:
  - docker

before_install:
  - docker build -t pebble/test-git-deploy .
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats

env:
  - DOCKER_HOST_IP=localhost

script:
  - bats test/test.bats