#!/bin/bash
source /opt/git-deploy/base-hooks/helpers.sh >> /var/log/git-deploy/hooks.log

while read oldrev newrev refname; do
	setup_env "$oldrev" "$newrev" >> /var/log/git-deploy/hooks.log
	if [ -f "$HOOK_DIR/post-receive" ]; then
		if [ "${CAPTURE_OUTPUT}" == "true" ]; then
			echo "$oldrev" "$newrev" "$refname" \
				| timeout -k "$DEPLOY_TIMEOUT_KILL" "$DEPLOY_TIMEOUT_TERM" \
					bash "$HOOK_DIR/post-receive" 2>&1 \
				| tee /var/log/git-deploy/hooks.log
		else
			echo "$oldrev" "$newrev" "$refname" \
				| timeout -k "$DEPLOY_TIMEOUT_KILL" "$DEPLOY_TIMEOUT_TERM" \
					bash "$HOOK_DIR/post-receive"
		fi
	fi
	/git/git-shell-commands/backup >> /var/log/git-deploy/hooks.log
done
