#!/bin/bash

source ~/.profile
set -o pipefail

if [ ! -z "$HOOK_REPO" ]; then
	hook_dir="/git/hooks"
else
	hook_dir="../hooks"
fi

[ ! -f "$hook_dir/update" ] || bash $hook_dir/update $@ | tee /var/log/git-deploy/hooks.log
