#!/bin/bash
source ~/.profile >> /var/log/git-deploy/hooks.log
set -o pipefail

unset GIT_DIR
cd ..

newrev="$3"

# source config.env from incoming HEAD if it exists
if git ls-tree --name-only -r $newrev 2>&1 | grep -qFx config.env; then
	# shellcheck disable=SC1090
	source <(git cat-file blob $newrev:config.env) >> /var/log/git-deploy/hooks.log
fi

# Update/use hooks from external repo if configured
if [ ! -z "$HOOK_REPO" ]; then
	if [ ! -z "$ENVIRONMENT" ]; then
		hook_dir="/git/${ENVIRONMENT}_hooks"
	else
		hook_dir="/git/hooks"
	fi
else
	hook_dir="hooks"
fi

[ ! -f "$hook_dir/update" ] || bash $hook_dir/update $@ | tee /var/log/git-deploy/hooks.log
