#!/bin/bash

# exit if we see 'badfile' in the list of files
# drop a breadcrumb and sleep if we see 'slowfile' in the list of files
while read oldrev newrev refname; do
	if [[ $oldrev =~ ^0+$ ]]; then
		FILES=$(git show --pretty="format:" --name-only $newrev)
	else
		FILES=$(git diff --name-only $oldrev..$newrev)
	fi

	# Launch an ssh agent to be nasty
	eval $(ssh-agent -s) 2>&1 > /dev/null
	trap "kill ${SSH_AGENT_PID}" EXIT

	for file in $FILES; do
		[ $file != 'badfile' ] || exit 1
		if [ "$file" == 'slowfile' ]; then
			touch breadcrumb
			sleep 5
			# pick up breadcrumb if it exists; fail if it was stolen (by a concurrent hook)
			[ -f breadcrumb ] && rm -f breadcrumb || exit 1
		fi
		if [ "$file" == 'stallfile' ]; then
			while [ true ]; do
				sleep 5
			done
		fi
	done
done
