#!/bin/bash

# exit if we see 'badfile' in the list of files
while read oldrev newrev refname; do
	if [[ $oldrev =~ 0+ ]]; then
		FILES=$(git show --pretty="format:" --name-only $newrev)
	else
		FILES=$(git diff --name-only $oldrev..$newrev)
	fi

	for file in $FILES; do
		[ $file != 'badfile' ] || exit 1
	done
done
